### ISSUE TITLE
Unknown format when parsing wav stretched by rubberband

### ISSUE THREAD

**Issue by binarykitchen** [rackfx/Node-WAV-File-Info#11]
Looks like there is a problem when parsing wav files that have been stretched by rubberband. Here an example error

```
{ error: true,
  invalid_reasons: [ 'Unknwon format: 22127' ],
  header: 
   { riff_head: 'RIFF',
     chunk_size: 6554,
     wave_identifier: 'WAVE',
     fmt_identifier: 'fmt ',
     subchunk_size: 3326,
     audio_format: 22127,
     num_channels: 1,
     sample_rate: 44100,
     byte_rate: 0,
     block_align: 2,
     bits_per_sample: 16,
     data_identifier: 'k\f\u0002\u001e' },
  stats: 
   { ... } }
```

Trying to grab the duration of the file here. Any clues?

**Comment by binarykitchen** [comment]
http://soundfile.sapp.org/doc/WaveFormat/ says

```
20        2   AudioFormat      PCM = 1 (i.e. Linear quantization)
                               Values other than 1 indicate some 
                               form of compression.
```

and since rubberband does stretch files, the format `22127` is probably valid and indicating some kind of compression?

**Comment by binarykitchen** [comment]
Btw, the ffmpeg command I used to generate that stretched wav file was

``
ffmpeg -thread_queue_size 2048 -i /home/michael-heuberger/binarykitchen/code/videomail.io/var/local/tmp/clients/videomail.io/11e6-aebd-f5430180-84c7-074d5706928b/videomail_preview.wav -y -acodec libvorbis -ac 1 -filter:a rubberband=tempo=1.454366279637038 -loglevel warning /home/michael-heuberger/binarykitchen/code/videomail.io/var/local/tmp/clients/videomail.io/11e6-aebd-f5430180-84c7-074d5706928b/videomail_preview_for_webm_stretched.wav
``

**Comment by drj-io** [comment]
Hi thanks for all the info!  

We'll take a look ASAP

**Comment by llogan** [comment]
Vorbis in WAV is an odd combination. Removing `-c:a libvorbis` from the command will solve the issue.

**Comment by binarykitchen** [comment]
right, that audio codec was unnecessary. 

but yeah, fixing the unknown typo would be good, thanks

**Comment by drj-io** [comment]
Thanks guys! We'll correct the typo.

**Comment by binarykitchen** [comment]
Thx
