### ISSUE TITLE
AIFF Fork

### ISSUE THREAD

**Issue by X-Raym** [rackfx/Node-WAV-File-Info#13]
Hi,
I see you use same function name for your AIFF fork, https://github.com/rackfx/Node-AIFF-File-Info, does this means that this Node-WAV-File-Info also works with .aiff ? What if I want to have wav & aiff analyses ? should I install both package ? Can they operate without conflict ?

Thanks for the precisions :)

**Comment by drj-io** [comment]
Yes, you can use them together as separate Node modules, with separate namespaces. You can just determine which is needed by the MIME type or extension of the file and use the appropriate validator (WAV or AIFF).

Thanks!
