### ISSUE TITLE
fs.open not a function

### ISSUE THREAD

**Issue by lararogu** [rackfx/Node-WAV-File-Info#14]
When I execute the infoByFilename function i get the error: fs.open is not a function.
I am using it in an angular project and I need the browserify.js to execute the fs=require('fs') dependency.

Any ideas?

**Comment by drj-io** [comment]
WFI was built for NodeJS to read a file on the server, not the browser. However, the approach is fairly simple, so if you can get all of the other dependancies working, you should be able to get it working with a file through the browser.  

You might want to try something like this: https://github.com/jvilk/BrowserFS\

Let me know if you have any success.

**Comment by lararogu** [comment]
I manage to make the 'fs' dependency work but now when I do the fs.open() i get the error:
Uncaught Error: ENOENT, no such file or directory '/audios'.
I take the file from a directory called 'audios' inside my project folder

**Comment by drj-io** [comment]
is /audios a web accessible directory?  I'm not sure about how you're doing this or using FS in the browser, so I don't know how much more I can help, unfortunately.

**Comment by lararogu** [comment]
the fs.open() method looks for the file in which directory? Does it look for it in the same directory where the  wfi.js file is located?
