### ISSUE TITLE
Locked files

### ISSUE THREAD

**Issue by adrydez** [rackfx/Node-WAV-File-Info#17]
Hi everybody,

I love your module and I included it in my application.
I found an issue. The audio files, after checked and extract the data, it blocks the audio files.
For example, if I have a file in a folder and I try to transform it from mono to stereo format, it results impossible to save it.
For tranform it, I use Adobe Audition. After the check by your module, if I open the file in the editor and I try to save, the application says "The file is used from another application".

There is a method to release the files?
Thx

**Comment by plefebvre91** [comment]
@adrydez  The OS locks the file because the lib doesn't close it properly. I think this is the same problem as #16

**Comment by drj-io** [comment]
fixed in 0.0.9
