### ISSUE TITLE
The library never closes the open file, leaking file descriptors.

### ISSUE THREAD

**Issue by mattdimeo** [rackfx/Node-WAV-File-Info#18]
Title says it all; the code opens files with fs.open and never closes them.  This leaks file descriptors and will eventually break the process once it runs out.

**Comment by mattdimeo** [comment]
I see you already have a fix for this; however, it has not been published to NPM, and the NPM version 0.0.8 is different from the current 0.0.8.

**Comment by drj-io** [comment]
interesting thanks for the feedback, will check it out.

**Comment by plefebvre91** [comment]
Problem still exists today. I use this module (from NPM), version 0.0.8, the `infoByFilename` function let the file open at the end, and OS locks the file...

Is it envisaged to fix the problem ?

**Comment by plefebvre91** [comment]
hello ? Is it possible to have an answer ? should I give up this library ? 😞

**Comment by mattdimeo** [comment]
I already gave up on it, but you can put a git link in your package.json rather than a version to call out the working head version, which appears to be checked in but not published to NPM.

**Comment by drj-io** [comment]
Sorry for the delay, I'll take a look at this tonight. It sounds like an easy fix on my end. Thanks!

**Comment by plefebvre91** [comment]
Thanks, it works !
