### ISSUE TITLE
Account for MULAW type 7

### ISSUE THREAD

**Issue by SPNilsen** [rackfx/Node-WAV-File-Info#21]
I have been using this library for a little time now to catalog a vast amount of WAV files I have saved locally.

I ran into an issue with some recently created audio files that have the MULAW format 0x0007 (7) which doesn't appear to be accounted for in the code.

This appears to be solved by adding additional ! checks into wav-file-info.js @line ~73 to account for Type 7 being valid.

Was there an intention to only including the Types that are listed? Thanks!

**Comment by drj-io** [comment]
We can certainly add it in, if it's valid WAV.  Did you want to submit a PR?

**Comment by SPNilsen** [comment]
PR sent with comments.
